version: 0.2

# Frontend Build - React/Vite
# Builds and deploys to S3 + invalidates CloudFront cache

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm ci

  pre_build:
    commands:
      - echo "Running lint..."
      - npm run lint || true

  build:
    commands:
      - echo "Building frontend..."
      - npm run build
      - echo "Build completed successfully"

  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync dist/ s3://${S3_BUCKET}/ --delete
      - |
        if [ -n "${CLOUDFRONT_DISTRIBUTION_ID}" ]; then
          echo "Invalidating CloudFront cache..."
          aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION_ID} --paths "/*"
        fi
      - echo "Frontend deployment completed!"

artifacts:
  files:
    - '**/*'
  base-directory: dist

cache:
  paths:
    - node_modules/**/*
