version: 0.2

# Backend Build - Python FastAPI
# Packages backend for CodeDeploy

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing Python dependencies..."
      - cd backend
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Running tests..."
      - cd backend
      - python -m pytest --tb=short -q || true

  build:
    commands:
      - echo "Packaging backend..."
      - cd backend
      - mkdir -p ../deploy
      - cp -r app ../deploy/
      - cp requirements.txt ../deploy/
      - cp run_worker.py ../deploy/ || true
      - echo "Backend package created"

  post_build:
    commands:
      - echo "Creating deployment artifacts..."
      - cp appspec.yml deploy/
      - cp -r scripts/deploy/ deploy/scripts/ || true
      - echo "Backend build completed!"

artifacts:
  files:
    - '**/*'
  base-directory: deploy
  discard-paths: no

cache:
  paths:
    - '/root/.cache/pip/**/*'
